#!/usr/bin/env python3
"""Apply generated Authentik blueprint via the Authentik API.

Waits for Authentik to be healthy, then creates (or updates) and applies the
homelab-sso blueprint generated by gen_authentik_blueprint.py.

Requires AUTHENTIK_BOOTSTRAP_TOKEN in .env for API authentication.

Can be imported (call apply()) or run standalone after the core stack is up:
  cd docker_compose/core && python3 apply_authentik_blueprint.py
"""

from __future__ import annotations

import json
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
STACK_DIR = SCRIPT_DIR.parent
REPO_ROOT = STACK_DIR.parent.parent
sys.path.insert(0, str(REPO_ROOT))

from scripts.homelab_common import load_env, log, resolve_config_base, setup_logging

BLUEPRINT_NAME = "homelab-sso"
AUTHENTIK_CONTAINER = "authentik-server"

# Healthcheck: wait up to this many seconds for Authentik to respond.
HEALTH_TIMEOUT_S = 120
HEALTH_POLL_INTERVAL_S = 5


def _get_container_ip(container: str) -> str | None:
    """Return the first IP address of a Docker container, or None."""
    try:
        result = subprocess.run(
            [
                "docker", "inspect", container,
                "--format",
                "{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}",
            ],
            capture_output=True,
            text=True,
            check=True,
        )
        ip = result.stdout.strip()
        return ip if ip else None
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _api(base_url: str, path: str, token: str,
         *, method: str = "GET", data: dict | None = None) -> dict | None:
    """Make an Authentik API request. Returns parsed JSON or None on error."""
    url = f"{base_url}{path}"
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            return json.loads(resp.read())
    except (urllib.error.URLError, urllib.error.HTTPError, OSError, json.JSONDecodeError) as exc:
        log.debug("API %s %s → %s", method, path, exc)
        return None


def _wait_for_healthy(base_url: str, token: str) -> bool:
    """Poll Authentik until it responds to an authenticated API call."""
    deadline = time.monotonic() + HEALTH_TIMEOUT_S
    log.info(
        "Waiting for Authentik to be ready (up to %ds)...", HEALTH_TIMEOUT_S
    )
    while time.monotonic() < deadline:
        result = _api(base_url, "/api/v3/core/applications/?page_size=1", token)
        if result is not None:
            log.info("Authentik API is ready.")
            return True
        time.sleep(HEALTH_POLL_INTERVAL_S)
    log.warning(
        "Authentik did not become ready within %ds. "
        "Blueprint will need to be applied manually.",
        HEALTH_TIMEOUT_S,
    )
    return False


def _find_existing_blueprint(base_url: str, token: str) -> str | None:
    """Return the pk of the existing homelab-sso blueprint, or None."""
    data = _api(base_url, "/api/v3/managed/blueprints/", token)
    if data is None:
        return None
    for bp in data.get("results", []):
        if bp.get("name") == BLUEPRINT_NAME:
            return bp["pk"]
    return None


def apply(env: dict[str, str], script_dir: Path) -> bool:
    """Apply the generated blueprint to Authentik via its API.

    Returns True on success, False if skipped or failed.
    """
    token = env.get("AUTHENTIK_BOOTSTRAP_TOKEN", "").strip()
    if not token:
        log.info(
            "AUTHENTIK_BOOTSTRAP_TOKEN not set; skipping automated blueprint apply. "
            "Apply manually via Customization → Blueprints → Create."
        )
        return False

    config_base = resolve_config_base(
        env.get("CONFIG_ROOT", "./config"), script_dir
    )
    blueprint_path = config_base / "authentik" / "blueprints" / "homelab-sso.yaml"
    if not blueprint_path.is_file():
        log.info(
            "No blueprint file found (no SSO entries in CADDY_EXTRA_SERVICES); "
            "skipping blueprint apply."
        )
        return False

    ip = _get_container_ip(AUTHENTIK_CONTAINER)
    if not ip:
        log.warning(
            "Could not determine %s container IP. "
            "Is the core stack running? Skipping blueprint apply.",
            AUTHENTIK_CONTAINER,
        )
        return False

    base_url = f"http://{ip}:9000"

    if not _wait_for_healthy(base_url, token):
        return False

    content = blueprint_path.read_text(encoding="utf-8")

    existing_pk = _find_existing_blueprint(base_url, token)

    if existing_pk:
        log.info("Updating existing blueprint '%s'...", BLUEPRINT_NAME)
        result = _api(
            base_url,
            f"/api/v3/managed/blueprints/{existing_pk}/",
            token,
            method="PATCH",
            data={"content": content, "enabled": True},
        )
    else:
        log.info("Creating blueprint '%s'...", BLUEPRINT_NAME)
        result = _api(
            base_url,
            "/api/v3/managed/blueprints/",
            token,
            method="POST",
            data={
                "name": BLUEPRINT_NAME,
                "path": "",
                "content": content,
                "enabled": True,
                "context": {},
            },
        )

    if result is None:
        log.error("Failed to create/update blueprint via API.")
        return False

    pk = result.get("pk", existing_pk)
    if not pk:
        log.error("Blueprint response missing pk.")
        return False

    log.info("Applying blueprint...")
    apply_result = _api(
        base_url,
        f"/api/v3/managed/blueprints/{pk}/apply/",
        token,
        method="POST",
    )

    if apply_result is None:
        log.error("Blueprint apply API call failed.")
        return False

    status = apply_result.get("status", "unknown")
    if status == "successful":
        log.info(
            "Authentik blueprint applied successfully "
            "(providers, applications, and outpost configured)."
        )
        return True
    else:
        log.warning("Blueprint apply returned status: %s", status)
        return status != "error"


def main() -> None:
    setup_logging()
    env_file = STACK_DIR / ".env"
    if not env_file.is_file():
        log.error(
            "No .env in %s; run bootstrap first or copy .env.example to .env.",
            STACK_DIR,
        )
        sys.exit(1)
    env = load_env(env_file)
    if not apply(env, STACK_DIR):
        sys.exit(1)


if __name__ == "__main__":
    main()