#!/usr/bin/env bash
# Core VM — first-run bootstrap (idempotent)
# Usage: cd docker_compose/core && ./bootstrap.sh [--up] [--force]
#
# Responsibilities:
#   1) Ensure .env exists (copy from .env.example on first run)
#   2) Validate critical env values (secrets/passwords not left as placeholders)
#   3) Create config directories for Caddy, Authentik, Postgres, Redis, dnsmasq
#   4) Create starter Caddyfile and dnsmasq.conf if missing
#   5) Optionally run docker compose up -d

set -e

FORCE=0
BRING_UP=0
for arg in "$@"; do
  [[ "$arg" = "--force" ]] && FORCE=1
  [[ "$arg" = "--up" ]] && BRING_UP=1
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "--- Core VM bootstrap ---"

# --- Prereqs ---
if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is not installed. Install Docker Engine first."
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "docker compose plugin not found. Install Docker Compose v2 plugin."
  exit 1
fi

# --- Env init ---
if [[ ! -f .env ]]; then
  if [[ -f .env.example ]]; then
    cp .env.example .env
    echo "Created .env from .env.example."
    echo "Edit .env with real values, then rerun bootstrap."
    exit 1
  else
    echo "Missing .env.example; cannot initialize .env."
    exit 1
  fi
fi

# shellcheck source=/dev/null
set -a && source ./.env && set +a

_is_placeholder() {
  local val="$1"
  [[ -z "$val" ]] && return 0
  [[ "$val" == CHANGE_ME* ]] && return 0
  [[ "$val" == "example.com" ]] && return 0
  return 1
}

# --- Guardrails ---
if [[ "$FORCE" -ne 1 ]]; then
  if _is_placeholder "${AUTHENTIK_SECRET_KEY:-}"; then
    echo "AUTHENTIK_SECRET_KEY is missing/placeholder in .env."
    echo "Generate one with: openssl rand -base64 60"
    exit 1
  fi
  if _is_placeholder "${AUTHENTIK_POSTGRES_PASSWORD:-}"; then
    echo "AUTHENTIK_POSTGRES_PASSWORD is missing/placeholder in .env."
    exit 1
  fi
  if _is_placeholder "${PUBLIC_BASE_DOMAIN:-}"; then
    echo "PUBLIC_BASE_DOMAIN still looks like example value."
    echo "Set your real domain, or rerun with --force for local testing."
    exit 1
  fi
fi

# --- Directories ---
CONFIG_BASE="${CONFIG_ROOT:-./config}"
[[ "$CONFIG_BASE" != /* ]] && CONFIG_BASE="$SCRIPT_DIR/$CONFIG_BASE"

mkdir -p \
  "$CONFIG_BASE/caddy" \
  "$CONFIG_BASE/caddy/data" \
  "$CONFIG_BASE/caddy/config" \
  "$CONFIG_BASE/caddy/site" \
  "$CONFIG_BASE/authentik/media" \
  "$CONFIG_BASE/authentik/custom-templates" \
  "$CONFIG_BASE/authentik/postgresql" \
  "$CONFIG_BASE/authentik/redis" \
  "$CONFIG_BASE/dnsmasq"

echo "Ensured config directories under: $CONFIG_BASE"

# --- Starter Caddyfile (only if missing) ---
CADDYFILE_PATH="$CONFIG_BASE/caddy/Caddyfile"
if [[ ! -f "$CADDYFILE_PATH" ]]; then
  cat > "$CADDYFILE_PATH" <<EOF
{
  # Keep ops noise low while retaining enough detail for troubleshooting.
  email admin@${PUBLIC_BASE_DOMAIN}
}

# Authentik web UI (proxied to internal Authentik server container).
${AUTHENTIK_FQDN} {
  encode zstd gzip
  reverse_proxy authentik-server:9000
}

# whoami debug endpoint (verifies front door, headers, and routing).
${WHOAMI_FQDN} {
  encode zstd gzip
  reverse_proxy whoami:80
}
EOF
  echo "Created starter Caddyfile: $CADDYFILE_PATH"
else
  echo "Caddyfile already exists; not overwriting."
fi

# --- Starter dnsmasq config (only if missing) ---
DNSMASQ_CONF_PATH="$CONFIG_BASE/dnsmasq/dnsmasq.conf"
if [[ ! -f "$DNSMASQ_CONF_PATH" ]]; then
  {
    echo "# dnsmasq starter config (generated by bootstrap.sh)"
    echo "# Keep this file small and explicit for predictable operations."
    echo "domain-needed"
    echo "bogus-priv"
    echo "no-resolv"
    echo "server=${DNS_UPSTREAM_1:-1.1.1.1}"
    echo "server=${DNS_UPSTREAM_2:-1.0.0.1}"
    echo "local=/${DNS_LOCAL_DOMAIN:-lab.arpa}/"
    echo "expand-hosts"
    echo "domain=${DNS_LOCAL_DOMAIN:-lab.arpa}"
    echo "cache-size=1000"
    echo ""
    echo "# Optional static records:"
    echo "# address=/apps.${DNS_LOCAL_DOMAIN:-lab.arpa}/192.168.1.120"
    echo "# address=/media.${DNS_LOCAL_DOMAIN:-lab.arpa}/192.168.1.130"
    if [[ -n "${DNS_LOCAL_RECORDS:-}" ]]; then
      OLD_IFS="$IFS"
      IFS=','
      for pair in $DNS_LOCAL_RECORDS; do
        host="${pair%%:*}"
        ip="${pair##*:}"
        if [[ -n "$host" ]] && [[ -n "$ip" ]] && [[ "$host" != "$ip" ]]; then
          echo "address=/${host}.${DNS_LOCAL_DOMAIN:-lab.arpa}/${ip}"
        fi
      done
      IFS="$OLD_IFS"
    fi
  } > "$DNSMASQ_CONF_PATH"
  echo "Created starter dnsmasq config: $DNSMASQ_CONF_PATH"
else
  echo "dnsmasq.conf already exists; not overwriting."
fi

# --- Validate compose ---
if ! docker compose -f "$SCRIPT_DIR/compose.yml" config >/dev/null; then
  echo "docker compose config validation failed."
  exit 1
fi
echo "Compose file validates successfully."

if [[ "$BRING_UP" -eq 1 ]]; then
  echo "Starting core stack..."
  docker compose -f "$SCRIPT_DIR/compose.yml" up -d
  echo "Core stack started."
else
  echo "Bootstrap complete. Run 'docker compose up -d' when ready."
fi
